@WebApi_HostAddress = http://localhost:5087

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/values

###
@myMalue = 123
POST {{WebApi_HostAddress}}/api/values/{{myMalue}}

###

POST {{WebApi_HostAddress}}/api/shoppinglists
Content-Type: application/json

{
  "Name": "moja lista"
}

###

GET {{WebApi_HostAddress}}/api/shoppinglists
Content-Type: application/json

###

POST {{WebApi_HostAddress}}/api/people
Content-Type: application/json

{
  "FirstName": "Ewa",
  "LastName": "Ewowoska",
  "Age": "54"
}

###

GET {{WebApi_HostAddress}}/api/people
Content-Type: application/json

###
DELETE {{WebApi_HostAddress}}/api/shoppinglists/1
Content-Type: application/json

###
DELETE {{WebApi_HostAddress}}/api/people/1
Content-Type: application/json

###
GET {{WebApi_HostAddress}}/api/people/search?firstName=ewa
Content-Type: application/json

###

GET {{WebApi_HostAddress}}/api/shoppinglists/1/Products
Content-Type: application/json

###

POST {{WebApi_HostAddress}}/api/shoppinglists/51/Products
Content-Type: application/json
 {
    "name": "jab³ko",
    "price": 15.50
  }
###
DELETE {{WebApi_HostAddress}}/api/Products/101
Content-Type: application/json

###